[book]
authors = ["Guilherme Junqueira"]
language = "en"
multilingual = false
src = "src"
title = "Solyd Pentest Handbook"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/guilhermej/pentest-handbook"
edit-url-template = "https://github.com/guilhermej/pentest-handbook/edit/main/{path}"
