[book]
authors = ["Guilherme Junqueira"]
language = "en"
multilingual = false
src = "src"
title = "Solyd Pentest Handbook"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/guilhermej/pentest-handbook"
git-repository-icon = "fa-github"

